version: "3.7"

networks:
  app:
    name: app

services:
  djangosite:
    build:
      context: ./
    image: djangosite:1.0.0
    container_name: djangosite
    env_file:
      - ./.env  
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./djangosite:/djangosite
    depends_on:
      - db

  db:
      image: postgres:15
      env_file:
        - ./.env   
      volumes:
        - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: